### ISSUE TITLE
会話の流れをプロンプト作り

### ISSUE THREAD

**Issue by Sakauchi444** [Sakauchi444/Hackit_team07#2]
ディベート形式みたいな？
他に形式あるかの調査も。

ちゃんと定まっていないので、しっかりと調査し、プロンプトを作成すること。

**Comment by 57tpp** [comment]
```
最初
あなたはディベートの参加者を演じてください。今回のテーマは「ディベートのテーマ」についてです。あなたは(賛成|反対)側として意見してください。あなたは三回発言ができ、そのうち最初の一回は500文字以内で(賛成側として立証|反対側として[賛成側の意見]この意見に反論)してださい。

二回目以降
(賛成|反対)側の意見です。反論してください。
[相手の意見]

```

**Comment by 57tpp** [comment]
```
あなたはディベートの審査員です。今回のテーマは「ディベートのテーマ」です。賛成派はAで、反対側がBです。双方の主張を見て、どちらがディベートの勝者であるか決定し、その理由を500字以内で述べて下さい。
```

**Comment by Sakauchi444** [comment]
プログラム側でもやってみた．
↓実行内容ベタ貼りします．
```
はい、ディベートのテーマについて賛成の立場から申し上げます。

現状、ディベートの際のテーマ設定が曖昧であるため、議論の方向性が定まりにくいという問題があると思います。テーマが明確でないと、参加者間で前提となる認識の対立が生じてしまい、建設的な議論に結びつきにくいではないでしょうか。

そこで私は、テーマ定める際のためらいを解き、明確なテーマ設定を行うことを提案します。具体的には、テーマを定める前に参加者間で共有すべき基本条件や前提条件を明確にし、その上でテーマを設定していただければと思います。テーマが明確になれば、議論の方向性が定まりますし、前提の相違から生じる混乱も回避できそうです。

テーマ設定が明確になれば、参加者一人一人が自らの主張を構成しやすくなる反面、既存の考え方にとらわれにくくなる可能性もあるでしょう。全体として建設的な議論を深められるメリットが大きいと私は考えます。それでは以上の3点を踏まえ、賛成の立場から申し上げました。
Traceback (most recent call last):
  File "/Users/hibi/dev/hackathon/poe-gpts/main.py", line 63, in <module>
    print(a[body][content].decode('unicode-escape'))
            ^^^^
NameError: name 'body' is not defined
(poe)
[hibi@hibi-mbp:~/dev/hackathon/poe-gpts]
$ python3 main.py
2024-03-13 22:47:32.503 | INFO     | poe_api_wrapper.api:send_message:752 - New Thread created | 24h54hk1n2c3kl4vyc2
 はい、賛成側として以下のように立論いたします。

現在のディベートのテーマ設定にはいくつかの課題があると思います。制限時間内で複数の論点をカバーしていただく必要があるため、深掘りできる内容が限られており、議論の質が低い部分があるのが現状だと思います。

また、テーマそのものが抽象的な場合が多く、参加者の間で共有される前提が必ずしも形成されにくいという課題も指摘できるでしょう。

これらの課題を解決するために、テーマ設定を単一のテーマに絞り込む提案です。時間が集中できる分、各自の主張を深化させる機会が増え、議論の質向上につながると考えます。

単一テーマにするメリットはこの通りである一方、テーマ選定の難しさや視点の狭さといった課題もあると思います。ただ、事前調整やテーマ設定ルールの改善を行えば、デメリットを minimized できると期待しています。

以上の視点から、単一テーマ設定への移行を支持いたします。参加者一人一人の能力最大限発揮と、より質的な議論を実現できる第一歩になると考えます。ご意見がありましたらぜひ補足いただければと思います。
Traceback (most recent call last):
  File "/Users/hibi/dev/hackathon/poe-gpts/main.py", line 63, in <module>
    print(a["body"]["content"].decode('unicode-escape'))
          ~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
(poe)
[hibi@hibi-mbp:~/dev/hackathon/poe-gpts]
$ python3 main.py
2024-03-13 22:55:39.050 | INFO     | poe_api_wrapper.api:send_message:752 - New Thread created | 24h6scj3gpermthy7uj
 はい、私から反対側としての意見を述べさせていただきます。

賛成側ではテーマ設定が曖昧で議論の方向性が定まりにくいという問題点を指摘していますが、私はその問題点が必ずしも重大ではないと考えます。ディベートの本質は様々な視点から議論を深めることです。テーマをあらかじめ厳密に定めることで、新たな視点の提起や議論の展開が阻害される可能性があります。

また、賛成側ではテーマ設定の明確化により前提条件の相違から生じる混乱を回避できるとしていますが、実際には前提条件自体が議論の対象になる場合があります。前提条件を明確に定めることで、建設的な対立が封じ込められてしまうリスクがあるでしょう。

加えて、テーマ設定の厳密化自体が現実的ではありません。ディベートの内容はテーマが提示されてから参加者同士で展開されていきます。一義的な答えがあるわけではなく、流動的な議論が望まれる場合が多いでしょう。

以上の理由から、私はテーマ設定の明確化が必ずしも建設的な議論につながるとは限らない、と考えます。むしろテーマ設定の幅を広く保つことの方が重要だと主張いたします。
{'statusCode': 200, 'body': '{"chatCode": "24h6scj3gpermthy7uj", "content": " はい、私から反対側としての意見を述べさせていただきます。\\n\\n賛成側ではテーマ設定が曖昧で議論の方向性が定まりにくいという問題点を指摘していますが、私はその問題点が必ずしも重大ではないと考えます。ディベートの本質は様々な視点から議論を深めることです。テーマをあらかじめ厳密に定めることで、新たな視点の提起や議論の展開が阻害される可能性があります。 \\n\\nまた、賛成側ではテーマ設定の明確化により前提条件の相違から生じる混乱を回避できるとしていますが、実際には前提条件自体が議論の対象になる場合があります。前提条件を明確に定めることで、建設的な対立が封じ込められてしまうリスクがあるでしょう。\\n\\n加えて、テーマ設定の厳密化自体が現実的ではありません。ディベートの内容はテーマが提示されてから参加者同士で展開されていきます。一義的な答えがあるわけではなく、流動的な議論が望まれる場合が多いでしょう。\\n\\n以上の理由から、私はテーマ設定の明確化が必ずしも建設的な議論につながるとは限らない、と考えます。むしろテーマ設定の幅を広く保つことの方が重要だと主張いたします。"}'}
(poe)
[hibi@hibi-mbp:~/dev/hackathon/poe-gpts]
$ python3 main.py
 はい、テーマ設定が曖昧であることによる弊害について賛成側が指摘する問題点はあると思います。しかし、ディベートの本質が様々な視点から議論を深めることである以上、過度にテーマを限定することで新たな視点の提起や議論の展開といった可能性が失われてしまうリスクの方が大きい、と私は考えます。

加えて、前提条件自体が議論の対象になる場面もあるでしょう。厳密なテーマ設定によって建設的な対立が封じ込められかねないでしょう。実際の議論はテーマ提示後に参加者同士で流動的に展開されるものだと思います。

以上の理由から、必ずしもテーマ設定の明確化が建設的な議論につながるとは限らないと考え、むしろテーマ設定の幅を広く保つべきである、と私は主張いたします。賛成側の指摘する問題点には理解を示しつつ、テーマ設定に関する私見を反論いたしました。chunk: {'id': 'TWVzc2FnZToxMzUwNDAyMTk0MjI=', 'messageId': 135040219422, 'creationTime': 1710338230562693, 'clientNonce': None, 'state': 'complete', 'text': ' はい、テーマ設定が曖昧であることによる弊害について賛成側が指摘する問題点はあると思います。しかし、ディベートの本質が様々な視点から議論を深めることである以上、過度にテーマを限定することで新たな視点の提起や議論の展開といった可能性が失われてしまうリスクの方が大きい、と私は考えます。 \n\n加えて、前提条件自体が議論の対象になる場面もあるでしょう。厳密なテーマ設定によって建設的な対立が封じ込められかねないでしょう。実際の議論はテーマ提示後に参加者同士で流動的に展開されるものだと思います。\n\n以上の理由から、必ずしもテーマ設定の明確化が建設的な議論につながるとは限らないと考え、むしろテーマ設定の幅を広く保つべきである、と私は主張いたします。賛成側の指摘する問題点には理解を示しつつ、テーマ設定に関する私見を反論いたしました。', 'author': 'a2', 'contentType': 'text_markdown', 'sourceType': 'chat_input', 'attachments': [], 'bot': {'displayName': 'Claude-instant', 'id': 'Qm90OjEwMDY=', 'handle': 'Claude-instant', 'nickname': 'a2', 'messageTimeoutSecs': 15, 'introduction': '', 'isApiBot': False, 'baseModelDisplayName': 'Claude-instant', 'botId': 1006, 'isPrivateBot': False, 'allowsImageAttachments': True, 'shouldHideLimitedAccessTag': False, 'deletionState': 'not_deleted', 'picture': {'__typename': 'LocalBotImage', 'localName': 'Avatar_Placeholder_Orange'}, '__isNode': 'Bot', 'canUserAccessBot': True, 'mayHaveSuggestedReplies': True, 'supportsResend': False, 'supportsRemix': False, 'isCreatedByPoeUserAccount': True}, 'vote': None, 'suggestedReplies': [], 'hasCitations': False, '__isNode': 'Message', 'textLengthOnCancellation': None, 'chatCode': {'24h54hk1n2c3kl4vyc2'}, 'chatId': None, 'title': None, 'response': '。'}
{'statusCode': 200, 'body': '{"chatCode": "24h54hk1n2c3kl4vyc2", "content": " はい、テーマ設定が曖昧であることによる弊害について賛成側が指摘する問題点はあると思います。しかし、ディベートの本質が様々な視点から議論を深めることである以上、過度にテーマを限定することで新たな視点の提起や議論の展開といった可能性が失われてしまうリスクの方が大きい、と私は考えます。 \\n\\n加えて、前提条件自体が議論の対象になる場面もあるでしょう。厳密なテーマ設定によって建設的な対立が封じ込められかねないでしょう。実際の議論はテーマ提示後に参加者同士で流動的に展開されるものだと思います。\\n\\n以上の理由から、必ずしもテーマ設定の明確化が建設的な議論につながるとは限らないと考え、むしろテーマ設定の幅を広く保つべきである、と私は主張いたします。賛成側の指摘する問題点には理解を示しつつ、テーマ設定に関する私見を反論いたしました。"}'}
(poe)

```

**Comment by Sakauchi444** [comment]
プログラムこんな感じ
```py
# python3 -m venv poe
# source poe/bin/activate
# pip3 install -U poe-api-wrapper

import json
from poe_api_wrapper import PoeApi
client = PoeApi("QBjYOY5ONFVv59P-B7HaOw%3D%3D")

# def lambda_handler(event, context):
def lambda_handler():
    # input
    # body = event["body"] # {"Name":"Tanaka", "Age":"100"}こんな感じのがくる．
    # conversation = body["conversation"]
    # chatCodeId = body["chatCodeId"] # 最初のリクエストは"０"がくる．
    # message = body["message"]
    # bot = body["bot"]
    # position = body["position"]

    # Kind of Bot Model
    bot = "a2"
    message = "反対側の意見です。500字以内で反論してください。賛成側ではテーマ設定が曖昧で議論の方向性が定まりにくいという問題点を指摘していますが、私はその問題点が必ずしも重大ではないと考えます。ディベートの本質は様々な視点から議論を深めることです。テーマをあらかじめ厳密に定めることで、新たな視点の提起や議論の展開が阻害される可能性があります。 \\n\\nまた、賛成側ではテーマ設定の明確化により前提条件の相違から生じる混乱を回避できるとしていますが、実際には前提条件自体が議論の対象になる場合があります。前提条件を明確に定めることで、建設的な対立が封じ込められてしまうリスクがあるでしょう。\\n\\n加えて、テーマ設定の厳密化自体が現実的ではありません。ディベートの内容はテーマが提示されてから参加者同士で展開されていきます。一義的な答えがあるわけではなく、流動的な議論が望まれる場合が多いでしょう。\\n\\n以上の理由から、私はテーマ設定の明確化が必ずしも建設的な議論につながるとは限らない、と考えます。むしろテーマ設定の幅を広く保つことの方が重要だと主張いたします。"
    chatCodeId = "24h54hk1n2c3kl4vyc2" # 賛成派
    # chatCodeId = "24h6scj3gpermthy7uj" # 反対派

    if chatCodeId == "0":
        # # Create new chat thread
        # # Streamed example:
        # for chunk in client.send_message(bot, message):
        #     print(chunk["response"], end="", flush=True)
        # print("\n 1 \n")

        # # Non-streamed example:
        for chunk in client.send_message(bot, message):
            pass
        print(chunk["text"])
        chatCode = chunk["chatCode"]

    else:
        # # You can get chatCode and chatId of created thread to continue the conversation
        # chatCode = chunk["chatCode"]
        # chatId = chunk["chatId"]
        # # You can get the meaningful title as well
        # title = chunk["title"]
        # print(f'chunk: {chunk}')
        # print(f'chatCode: {chatCode}, chatId: {chatId}, title:{title}')

        # Send message to an existing chat thread
        # 1. Using chatCode
        for chunk in client.send_message(bot, message, chatCode={chatCodeId}):
            print(chunk["response"], end="", flush=True)
        print(f'chunk: {chunk}')
        chatCode = chatCodeId

    # 応答を返す
    return {
        'statusCode': 200,
        'body': json.dumps({
            "chatCode": chatCode,
            "content": chunk["text"]
        }, ensure_ascii=False)
    }

a= lambda_handler()
print(a)
```

**Comment by Sakauchi444** [comment]
```py

# python3 -m venv poe
# source poe/bin/activate
# pip3 install -U poe-api-wrapper

import json
from poe_api_wrapper import PoeApi
client = PoeApi(<poe_api_key>)

# def lambda_handler(event, context):
def lambda_handler():
    # input
    # body = event["body"] # {"Name":"Tanaka", "Age":"100"}こんな感じのがくる．
    # conversation = body["conversation"]
    # chatCodeId = body["chatCodeId"] # 最初のリクエストは"０"がくる．
    # message = body["message"]
    # bot = body["bot"]
    # position = body["position"]

    # Kind of Bot Model
    bot = "a2"
    message = "反対側の意見です。500字以内で反論してください。賛成側ではテーマ設定が曖昧で議論の方向性が定まりにくいという問題点を指摘していますが、私はその問題点が必ずしも重大ではないと考えます。ディベートの本質は様々な視点から議論を深めることです。テーマをあらかじめ厳密に定めることで、新たな視点の提起や議論の展開が阻害される可能性があります。 \\n\\nまた、賛成側ではテーマ設定の明確化により前提条件の相違から生じる混乱を回避できるとしていますが、実際には前提条件自体が議論の対象になる場合があります。前提条件を明確に定めることで、建設的な対立が封じ込められてしまうリスクがあるでしょう。\\n\\n加えて、テーマ設定の厳密化自体が現実的ではありません。ディベートの内容はテーマが提示されてから参加者同士で展開されていきます。一義的な答えがあるわけではなく、流動的な議論が望まれる場合が多いでしょう。\\n\\n以上の理由から、私はテーマ設定の明確化が必ずしも建設的な議論につながるとは限らない、と考えます。むしろテーマ設定の幅を広く保つことの方が重要だと主張いたします。"
    chatCodeId = "24h54hk1n2c3kl4vyc2" # 賛成派
    # chatCodeId = "24h6scj3gpermthy7uj" # 反対派

    if chatCodeId == "0":
        # # Create new chat thread
        # # Streamed example:
        # for chunk in client.send_message(bot, message):
        #     print(chunk["response"], end="", flush=True)
        # print("\n 1 \n")

        # # Non-streamed example:
        for chunk in client.send_message(bot, message):
            pass
        print(chunk["text"])
        chatCode = chunk["chatCode"]

    else:
        # # You can get chatCode and chatId of created thread to continue the conversation
        # chatCode = chunk["chatCode"]
        # chatId = chunk["chatId"]
        # # You can get the meaningful title as well
        # title = chunk["title"]
        # print(f'chunk: {chunk}')
        # print(f'chatCode: {chatCode}, chatId: {chatId}, title:{title}')

        # Send message to an existing chat thread
        # 1. Using chatCode
        for chunk in client.send_message(bot, message, chatCode={chatCodeId}):
            print(chunk["response"], end="", flush=True)
        print(f'chunk: {chunk}')
        chatCode = chatCodeId

    # 応答を返す
    return {
        'statusCode': 200,
        'body': json.dumps({
            "chatCode": chatCode,
            "content": chunk["text"]
        }, ensure_ascii=False)
    }

a= lambda_handler()
print(a)
```
